### ISSUE TITLE
"djmoney_rates_ratesource" does not exist

### ISSUE THREAD

**Issue by astarrh** [evonove/django-money-rates#7]
Hello, 
I installed this package as instructed via pip. Any attempt to use the example method or update currency produces the following:

    django.db.utils.ProgrammingError: relation "djmoney_rates_ratesource" does not exist
    LINE 1: ..., "djmoney_rates_ratesource"."base_currency" FROM "djmoney_r..

Specs:
Windows 7
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)] on win32
Django 1.8.2
py-moneyed 0.5.0

**Comment by Psykopear** [comment]
have you tried to run the migrations?

2015-06-12 14:34 GMT+02:00 astarrh <notifications@github.com>:

**Comment by astarrh** [comment]
Sorry to bother. My test server was running on the wrong virtual environment :/
